if(EXISTS "/home/aymane/Desktop/OrbitalForge/build-release/orbitalforge_tests-b12d07c_tests.cmake")
  include("/home/aymane/Desktop/OrbitalForge/build-release/orbitalforge_tests-b12d07c_tests.cmake")
else()
  add_test(orbitalforge_tests_NOT_BUILT-b12d07c orbitalforge_tests_NOT_BUILT-b12d07c)
endif()
